rhizome/api/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns
import views as api_views

from api.views import LoginView, LogoutView, PasswordChangeView

urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^password/change/$', PasswordChangeView.as_view()),

]

rhizome/rhizome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from customer.views import index_view

admin.autodiscover()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^grappelli/', include('grappelli.urls')),

    # rest framework urls
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/auth/', include('api.urls', namespace='api_auth_url')),
    url(r'^sb/', include('storyboard.urls', namespace='storyboard_url')),
    url(r'^user/', include('customer.urls', namespace='customer_url')),
    url(r'^$', index_view, name='index_url'),
]

rhizome/storyboard/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from storyboard.api import TestStoryboard, StoryboardApi
from storyboard.views import render_storyboard_web
from storyboard.views import ExperienceTemplateList, ExperienceWizardView
from storyboard.views import PublishWizardView, StoryboardListView

urlpatterns = [

    url(r'^test/$', TestStoryboard.as_view(), name='test_storyboard'),
    url(r'^create/step1/$', ExperienceTemplateList.as_view(), name='experience_template_list_view'),
    url(r'^create/step2/$', ExperienceWizardView.as_view(), name='experience_wizard_view'),
    url(r'^share/(?P<sid>[a-zA-Z0-9\-]+)/$', PublishWizardView.as_view(), name='publish_wizard_view'),
    url(r'^list/$', StoryboardListView.as_view(), name='storyboard_list_view'),
    url(r'^(?P<csb_guid>[a-zA-Z0-9\-]+)/$', render_storyboard_web, name='render_storyboard_web'),
    url(r'^_api/(?P<csb_guid>[a-zA-Z0-9\-]+)/$', StoryboardApi.as_view(), name='storyboard_api_view'),
]

rhizome/storyboard/models.py
from __future__ import unicode_literals

from django.db import models
import logging
import uuid
from customer.models import Customer
from django.conf import settings
import os
from django.core.urlresolvers import reverse

logger = logging.getLogger(__name__)


class ExperienceTemplate(models.Model):

    guid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, db_index=True)
    name = models.CharField(max_length=255, unique=True, null=False, blank=False)
    description = models.TextField(blank=True)
    meta_file = models.CharField(max_length=255, null=False, blank=False)
    web_template = models.CharField(max_length=255, null=True, blank=True)
    vr_template = models.CharField(max_length=255, null=True, blank=True)
    mobile_template = models.CharField(max_length=255, null=True, blank=True)
    embed_template = models.CharField(max_length=255, null=True, blank=True)
    thumbnail = models.URLField(max_length=255, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return "%s<---->%s" % (self.guid, self.name)

    def get_meta_file_path(self):
        return os.path.join(settings.BASE_DIR, self.meta_file)


class ExperienceTemplateCollection(models.Model):

    experience_template = models.ForeignKey(ExperienceTemplate)
    collection = models.CharField(max_length=200, null=False, blank=False)

    def __unicode__(self):
        return "%s:%s <--> %s" % (self.experience_template.guid, self.experience_template.name, self.collection)


class CustomerStoryboard(models.Model):

    DRAFT = 'DR'
    PUBLISHED = 'PB'
    ARCHIVED = 'AR'
    DELETED = 'DL'
    PUB_STATES = (
        (DRAFT, 'Draft'),
        (PUBLISHED, 'Published'),
        (ARCHIVED, 'Archived'),
        (DELETED, 'Deleted'),
    )

    guid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, db_index=True)
    name = models.CharField(max_length=255, null=False, blank=False)
    current_state = models.CharField(max_length=2,
                                     choices=PUB_STATES,
                                     default=DRAFT)
    experience_template = models.ForeignKey(ExperienceTemplate)
    customer = models.ForeignKey(Customer)
    storyboard_id = models.CharField(max_length=255, null=False, blank=False)
    is_private = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    published_at = models.DateTimeField(blank=True, null=True)

    class Meta:
        ordering = ["-created_at"]

    def __unicode__(self):
        return "%s:%s <--> %s <--> %s" % (self.guid, self.name, self.customer, self.current_state)

    def get_absolute_url(self):
        return reverse('storyboard_url:render_storyboard_web', args=[str(self.guid)])

rhizome/storyboard/controllers.py
import logging
from django.conf import settings
from jinja2 import Environment, FileSystemLoader
import json

logger = logging.getLogger(__name__)
env = Environment(loader=FileSystemLoader(settings.STORYBOARD_TEMPLATES_PATH))


class StoryboardController:

    @staticmethod
    def get_test_storyboard():
        """ generate a test storyboard """

        templ = env.get_template("test.j2")
        resp_string = templ.render(baseColor="#A4AB4B", title="Knowlarity",
                                   logoUrl="https://static-assets.knowlarity.com/wp-content/uploads/2014/04/logo.png",
                                   tagline="GIVING BUSINESS A VOICE",
                                   templateId=2)
        return json.loads(resp_string)

rhizome/storyboard/views.py
from django.shortcuts import render, redirect
from storyboard.mgmodels import Storyboard
from storyboard.models import ExperienceTemplate, CustomerStoryboard
from django.views.generic import ListView
from django.views.generic import View
from django.shortcuts import get_object_or_404
import json
from customer.models import Customer
from django.core.mail import send_mail
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.models import Site
import logging

logger = logging.getLogger(__name__)


def context_mapper(storyboard):
    """ creates an easily parsable context object from storyboard, mostly to
        ease handling in django templates """

    ret_hash = {}

    for dzname in storyboard['mappings'].keys():
        ret_hash[dzname] = {
            'dropzoneType': storyboard['mappings'][dzname]['dropzoneType'],
            'data': [storyboard['objects'][obj_id] for obj_id in storyboard['mappings'][dzname]['objects']]
        }
    return ret_hash


def render_storyboard_web(request, csb_guid):
    """ display the storyboard according to the template specified
        TODO: fix the way template file is picked up. Perhaps provide it in settings.
    """

    csb = get_object_or_404(CustomerStoryboard, guid=csb_guid)
    sb = Storyboard.get(csb.storyboard_id)

    if sb:
        context = context_mapper(sb.storyboard)
        return render(request, csb.experience_template.web_template, context)
    else:
        raise Http404("Storyboard does not exist")


class ExperienceTemplateList(LoginRequiredMixin, ListView):

    login_url = '/user/login/'
    redirect_field_name = 'redirect_to'
    model = ExperienceTemplate
    template_name = 'internal/create_experience_step1.html'


class ExperienceWizardView(LoginRequiredMixin, View):

    login_url = '/user/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):
        """ returns the template meta information to generate the wizard """

        exp_model = get_object_or_404(ExperienceTemplate, guid=request.GET['tid'])
        with open(exp_model.get_meta_file_path()) as f:
            templ_meta = json.loads(f.read())
        context = {
            'template_meta': templ_meta,
            'experience_template': exp_model
        }
        return render(request, 'internal/create_experience_step2.html', context)

    def post(self, request, *args, **kwargs):
        """ creates the storyboard based on dropzone values entered by the user """

        exp_model = get_object_or_404(ExperienceTemplate, guid=request.GET['tid'])
        with open(exp_model.get_meta_file_path()) as f:
            templ_meta = json.loads(f.read())

        title = request.POST.get('title')
        logo = request.POST.get('logo')

        sb_obj = Storyboard(title=title, logo=logo, template_id=exp_model.guid)

        for dzname in templ_meta['dropzones'].keys():

            if templ_meta['dropzones'][dzname]['dropzoneType'] == 'TEXT':
                obj_id = sb_obj.add_text(request.POST.get(dzname))
                sb_obj.add_mapping(dzname, 'TEXT', [obj_id])

            elif templ_meta['dropzones'][dzname]['dropzoneType'] == 'IMAGE':
                obj_id = sb_obj.add_image(url=request.POST.get(dzname), thumbnail=request.POST.get(dzname), width=500,
                                          height=300)
                sb_obj.add_mapping(dzname, 'IMAGE', [obj_id])

            elif templ_meta['dropzones'][dzname]['dropzoneType'] == 'IMAGE-GROUP':
                image_urls = request.POST.get(dzname).split(',')
                obj_arr = []
                for url in image_urls:
                    obj_id = sb_obj.add_image(url=url, thumbnail=url, width=500, height=300)
                    obj_arr.append(obj_id)
                sb_obj.add_mapping(dzname, 'IMAGE', obj_arr)

            elif templ_meta['dropzones'][dzname]['dropzoneType'] == 'VIDEO-GROUP':
                video_urls = request.POST.get(dzname).split(',')
                obj_arr = []
                for url in video_urls:
                    obj_id = sb_obj.add_video(url=url, thumbnail=url, width=500, height=300)
                    obj_arr.append(obj_id)
                sb_obj.add_mapping(dzname, 'VIDEO', [obj_id])

        print sb_obj.storyboard
        sb_obj.save()

        if sb_obj.storyboard_id is not None:
            customer = Customer.objects.filter()[0]
            customer_sb = CustomerStoryboard(name=title, experience_template=exp_model, customer=customer,
                                             storyboard_id=sb_obj.storyboard_id)
            customer_sb.save()
            return redirect('storyboard_url:publish_wizard_view', sid=customer_sb.guid)

        context = {
            'template_meta': templ_meta,
            'experience_template': exp_model
        }
        return render(request, 'internal/create_experience_step2.html', context)


class PublishWizardView(LoginRequiredMixin, View):

    login_url = '/user/login/'
    redirect_field_name = 'redirect_to'

    def get(self, request, *args, **kwargs):
        """ handles the final step of the experience creation process """

        s_guid = kwargs['sid']
        sb = get_object_or_404(CustomerStoryboard, guid=s_guid)

        context = {
            'storyboard': sb
        }
        return render(request, 'internal/create_experience_step3.html', context)

    def post(self, request, *args, **kwargs):
        """ sends emails to a list of email addresses provided
            TODO: move emails to async task. Verify email addresses. Perhaps put a form validation.
        """

        s_guid = kwargs['sid']
        sb = get_object_or_404(CustomerStoryboard, guid=s_guid)

        if 'emails' in request.POST:
            emails = request.POST.get('emails').split(',')
            for email in emails:
                subj = "Check out " + sb.name
                body = "A sixthdot experience has been privately shared with you. You can see it at http://%s%s" % (Site.objects.get_current().domain, sb.get_absolute_url())
                if 'email_message' in request.POST and len(request.POST.get('email_message')) > 0:
                    body = body + "\nThe sender added the following private note:\n"
                    body = body + request.POST.get('email_message')
                send_mail(subj, body, 'noreply@viewfieldlabs.net', [email])
            print request.POST.get('email_message')

        context = {
            'storyboard': sb
        }
        return render(request, 'internal/create_experience_step3.html', context)


class StoryboardListView(LoginRequiredMixin, ListView):

    login_url = '/user/login/'
    redirect_field_name = 'redirect_to'
    model = CustomerStoryboard
    template_name = 'internal/mystoryboards.html'

rhizome/storyboard/templates/internal/create_experience_step1.html
{% extends 'internal/layout.html' %}

{% block content %}
    <!-- Page Content -->
    <div class="container">

        <!-- Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Step 1
                    <small>Choose Experience Template</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->

        <div class="row">
            {% for exp_templ in object_list %}
            <div class="col-md-6 portfolio-item">
                <a href="#">
                    <img class="img-responsive" src="{{ exp_templ.thumbnail }}" alt="">
                </a>
                <h3>
                    <a href="{% url 'storyboard_url:experience_wizard_view' %}?tid={{ exp_templ.guid }}">{{ exp_templ.name }}</a>
                </h3>
                <p>{{ exp_templ.description }}</p>
            </div>
            {% endfor %}
        </div>
        <!-- /.row -->
{% endblock %}

rhizome/storyboard/templates/internal/create_experience_step2.html
{% extends 'internal/layout.html' %}

{% block content %}
<!-- Page Content -->
<div class="container">

    <!-- Page Header -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Step 2
                <small>Customize Experience With Details</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <!-- Projects Row -->

    <div class="row">
        <div class="col-md-6">
            <form role="form" method="POST" action="{% url 'storyboard_url:experience_wizard_view' %}?tid={{ experience_template.guid }}">
                {% csrf_token %}

                <div class="form-group">
                    <label>Title</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>

                <div class="form-group">
                    <label>Logo</label>
                    <input type="text" class="form-control" id="logo" name="logo">
                </div>

                {% for dzname,dzmeta in template_meta.dropzones.items %}
                  <div class="form-group">
                      {% if dzmeta.dropzoneType == 'IMAGE' %}
                          <label>{{ dzmeta.meta.name }}</label>
                          <input type="text" class="form-control" id="{{ dzname }}" name="{{ dzname }}">
                      {% elif dzmeta.dropzoneType == 'TEXT' %}
                          <label>{{ dzmeta.meta.name }}</label>
                          <input type="text" class="form-control" id="{{ dzname }}" name="{{ dzname }}">
                      {% elif dzmeta.dropzoneType == 'VIDEO' %}
                          <label>{{ dzmeta.meta.name }}</label>
                          <input type="text" class="form-control" id="{{ dzname }}" name="{{ dzname }}">
                      {% elif dzmeta.dropzoneType == 'IMAGE-GROUP' %}
                          <label>{{ dzmeta.meta.name }}</label>
                          <textarea class="form-control" id="{{ dzname }}" name="{{ dzname }}"></textarea>
                      {% elif dzmeta.dropzoneType == 'VIDEO-GROUP' %}
                          <label>{{ dzmeta.meta.name }}</label>
                          <textarea class="form-control" id="{{ dzname }}" name="{{ dzname }}"></textarea>
                      {% endif %}
                  </div>
                {% endfor %}
              <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </div>

        <div class="col-md-6 portfolio-item">
            <a href="#">
                <img class="img-responsive" src="{{ experience_template.thumbnail }}" alt="">
            </a>
            <h3>
                {{ experience_template.name }}
            </h3>
            <p>{{ experience_template.description }}</p>
        </div>
    </div>

</div>

{% endblock %}

rhizome/storyboard/templates/internal/create_experience_step3.html
{% extends 'internal/layout.html' %}

{% block content %}
<!-- Page Content -->
<div class="container">

    <!-- Page Header -->
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Share
                <small>Share the experience privately or publicly</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <div class="row">
      <ul class="nav nav-tabs">
        <li class="active"><a href="#">Web</a></li>
        <li><a href="#">Vr / 3d</a></li>
      </ul>
      <div class="tabcontent">
          <iframe class="col-lg-12 dotted-border preview-content" src="{{ storyboard.get_absolute_url }}">You need an iframe capable browser</iframe>
          <div class="col-lg-6">
            <div class="secondary-content">
              <h6 class="inline-title copy-zone">
                <a href="{{ storyboard.get_absolute_url }}">{{ storyboard.get_absolute_url }}</a>
              </h6>
              <br>
              <span>
                <i class="fa fa-twitter" aria-hidden="true"></i>
                <i class="fa fa-facebook" aria-hidden="true"></i>
                <i class="fa fa-twitter" aria-hidden="true"></i>
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </span>
            </div>
            <form method="POST" action="{% url 'storyboard_url:publish_wizard_view' sid=storyboard.guid %}">
                {% csrf_token %}
                <div class="form-group">
                    <label>Share privately</label>
                    <input type="text" class="form-control" id="emails" name="emails">
                </div>
                <div class="form-group">
                    <label>Add a personal message</label>
                    <textarea class="form-control" id="email_message" name="email_message"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Send</button>
            </form>
        </div>
      </div>
    </div>
    <!-- Projects Row -->

</div>
{% endblock %}

rhizome/storyboard/templates/internal/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Choose Experience Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/flat-ui.css" %}" rel="stylesheet">

    <!--- Font awesome -->
    <link href="{% static "font-awesome/css/font-awesome.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/2-col-portfolio.css" %}" rel="stylesheet">
    <link href="{% static "css/custom-sagar.css" %}" rel="stylesheet">


    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <!-- Navigation -->
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">.:sixthdot:.</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li>
                        <a href="{% url 'storyboard_url:storyboard_list_view' %}">Browse</a>
                    </li>
                    <li>
                        <a href="{% url 'storyboard_url:experience_template_list_view' %}">Create</a>
                    </li>
                    <li>
                        <a href="#">Track</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    {% block content %}

    {% endblock %}

    <hr>

    <!-- Footer -->
    <footer>
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; Your Website 2014</p>
            </div>
        </div>
        <!-- /.row -->
    </footer>

</div>
<!-- /.container -->

<!-- jQuery -->
<script src="{% static "js/jquery.js" %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static "js/bootstrap.min.js" %}"></script>

</body>

</html>

rhizome/storyboard/templates/internal/mystoryboards.html
{% extends 'internal/layout.html' %}

{% block content %}
    <!-- Page Content -->
    <div class="container">

        <!-- Page Header -->
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Browse
                    <small>All the showcases you have created</small>
                </h1>
            </div>
        </div>
        <!-- /.row -->

        <!-- Projects Row -->

        <div class="row">
            {% for sb in object_list %}
            <div class="col-md-6 portfolio-item">
                <a href="{{ sb.get_absolute_url }}">
                    <img class="img-responsive" src="{{ sb.experience_template.thumbnail }}" alt="">
                </a>
                <h3>
                    <a href="{% url 'storyboard_url:render_storyboard_web' csb_guid=sb.guid %}">{{ sb.name }}</a>
                </h3>
            </div>
            {% endfor %}
        </div>
        <!-- /.row -->


{% endblock %}