rhizome/api/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static

from rest_framework.urlpatterns import format_suffix_patterns
import views as api_views

from api.views import LoginView, LogoutView, PasswordChangeView

urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),
    url(r'^password/change/$', PasswordChangeView.as_view()),

]

rhizome/customer/urls.py
from django.conf import settings
from django.contrib import admin
from django.conf.urls import include, url
from django.conf.urls.static import static
from customer.views import LoginView, SignupView, VideoView


urlpatterns = [

    url(r'^login/$', LoginView.as_view(), name='login_view'),
    url(r'^signup/$', SignupView.as_view(), name='signup_view'),
    url(r'^video/$', VideoView.as_view(), name='video_view'),
]

rhizome/rhizome/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from customer.views import index_view

admin.autodiscover()


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^grappelli/', include('grappelli.urls')),

    # rest framework urls
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^api/v1/auth/', include('api.urls', namespace='api_auth_url')),
    url(r'^sb/', include('storyboard.urls', namespace='storyboard_url')),
    url(r'^user/', include('customer.urls', namespace='customer_url')),
    url(r'^$', index_view, name='index_url'),
]

rhizome/customer/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from rest_framework.authtoken.models import Token
import uuid
import logging

logger = logging.getLogger(__name__)

class Customer(models.Model):

    guid =  models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, db_index=True)
    user = models.OneToOneField(User, db_index=True, related_name="customer")
    name = models.CharField(max_length=200, null=True, blank=True)
    mobile = models.CharField(max_length=15,  null=True, blank=True)
    email = models.EmailField(max_length=300, null=True, blank=False, db_index=True)
    org  = models.CharField(max_length=15,  null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # mobile user id used for push notifications and identifying users
    mobile_user_id = models.CharField(max_length=200, null=True, blank=True)
    mobile_device_id = models.CharField(max_length=200, null=True, blank=True)

    def __unicode__(self):

        return "%s<---->%s" %(self.guid, self.email)


# post save for creating customer on user saving
def create_customer(sender, instance, created, **kwargs):
    
    # create customer instance 
    if created:

        customer, created = Customer.objects.get_or_create(user=instance, email=instance.email)

        # create token for user for mobile APIs
        
        user = customer.user
        token = Token.objects.create(user=user)
        logger.info("Created token for user %s : %s" %(user, token))
    

post_save.connect(create_customer, sender=User)

rhizome/customer/views.py
from django.shortcuts import render
from django.views.generic import View
from django.shortcuts import render, redirect

# Create your views here.


class LoginView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, 'internal/login.html', context)


class SignupView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, 'internal/registration.html', context)


class VideoView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        return render(request, 'internal/video_player.html', context)


def index_view(request):
    context = {}
    return render(request, 'internal/index.html', context)

rhizome/customer/templates/internal/login.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Choose Experience Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/flat-ui.css" %}" rel="stylesheet">


    <!-- Custom CSS -->
    <link href="{% static "css/2-col-portfolio.css" %}" rel="stylesheet">
    <link href="{% static "css/custom-sagar.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="bgImage">

    {% block content %}

    {% endblock %}

    <div class="container">
    <div class="row">
    	<div class="col-md-4 col-md-offset-4">

    		<div class="panel panel-inverse positionMe">
          <div class="panel-heading">
            <h6>Sixth<strong>dot</strong> Login</h6>
          </div>
			  	<div class="panel-body">
			    	<form accept-charset="UTF-8" role="form">
                    <fieldset>
			    	  	<div class="form-group">
			    		    <input class="form-control" placeholder="yourmail@example.com" name="email" type="text">
			    		</div>
			    		<div class="form-group">
			    			<input class="form-control" placeholder="Password" name="password" type="password" value="">
			    		</div>
			    		<div class="checkbox">
			    	    	<label>
			    	    		<input name="remember" type="checkbox" value="Remember Me"> Remember Me
			    	    	</label>
			    	    </div>
			    		<input class="btn btn-lg btn-inverse btn-block" type="submit" value="Login">
			    	</fieldset>
			      	</form>
                      <hr/>
                <center><h4>OR</h4></center>
                <a class="btn btn-lg  btn-primary btn-facebook btn-block" type="submit" value="Register" href="{% url 'customer_url:signup_view' %}">Signup</a>
			    </div>
			</div>
		</div>
	</div>
</div>

<!-- /.container -->

<!-- jQuery -->
<script src="{% static "js/jquery.js" %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static "js/bootstrap.min.js" %}"></script>

</body>

</html>

rhizome/customer/templates/internal/registration.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Choose Experience Template</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static "css/flat-ui.css" %}" rel="stylesheet">


    <!-- Custom CSS -->
    <link href="{% static "css/2-col-portfolio.css" %}" rel="stylesheet">
    <link href="{% static "css/custom-sagar.css" %}" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body class="bgImage">

    {% block content %}

    {% endblock %}

    <div class="container">
     <div class="row">
        <div class="col-md-4 col-md-offset-4">
           <div class="panel panel-inverse registration-panel">
              <div class="panel-heading">
                 <h6>Sixth<strong>dot</strong> Registration</h6>
              </div>
              <div class="panel-body">
                 <form accept-charset="UTF-8" role="form">
                    <fieldset>
                       <div class="form-group">
                         <label class="form">Work Email</label>
                          <input class="form-control" placeholder="yourmail@example.com" name="email" type="text">
                       </div>
                       <div class="form-group">
                         <label class="form">Full Name</label>
                          <input class="form-control" placeholder="Name" name="password" type="text" value="">
                       </div>

                       <div class="form-group">
                         <label class="form">Password</label>
                          <input class="form-control" placeholder="Password" name="password" type="password" value="">
                       </div>

                       <div class="form-group">
                         <label class="form">Your Designation</label>
                         <select class="form-control select select-primary">
                             <option value="0">Partner</option>
                             <option value="1">My Friends</option>
                          </select>
                       </div>

                       <div class="form-group">
                         <label class="form">Phone Number</label>
                          <input class="form-control" placeholder="#" name="password" type="number" value="">
                       </div>

                       <input class="btn btn-lg btn-primary btn-block" type="submit" value="Register">
                    </fieldset>
                 </form>
              </div>
           </div>
        </div>
     </div>
  </div>

<!-- /.container -->

<!-- jQuery -->
<script src="{% static "js/jquery.js" %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static "js/bootstrap.min.js" %}"></script>

</body>

</html>